version: '3.8'

name: stori-rag-challenge

services:
  postgres:
    container_name: stori-rag-challenge-postgresql
    image: pgvector/pgvector:0.8.0-pg17
    ports:
      - 5432:5432
    command: -p 5432
    env_file:
      - .env.docker

  api:
    container_name: stori-rag-challenge-api
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env.docker
    depends_on:
      - postgres