"""SessionOverview

Revision ID: d35dc5f9a3b0
Revises:
Create Date: 2025-02-18 20:20:35.820512

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d35dc5f9a3b0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_overview",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("auto_faithfulness", sa.Float(), nullable=True),
        sa.Column("auto_relevance", sa.Float(), nullable=True),
        sa.Column("auto_correctness", sa.Float(), nullable=True),
        sa.Column("auto_comments", sa.String(), nullable=True),
        sa.Column("human_faithfulness", sa.Float(), nullable=True),
        sa.Column("human_relevance", sa.Float(), nullable=True),
        sa.Column("human_correctness", sa.Float(), nullable=True),
        sa.Column("human_comments", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_index(
        op.f("ix_session_overview_id"),
        "session_overview",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_session_overview_id"), table_name="session_overview"
    )
    op.drop_table("session_overview")
    # ### end Alembic commands ###
